### PR TITLE
modified auto-mode-alist

### PR DESCRIPTION
**Pull request by sensorflo**
See commit messages

### CODE REVIEW

**Comment by tarsius** [comment]
I'm not sure we really need those comments.

**Comment by sensorflo** [comment]
Granted, they are not really needed. I just found the comments helpful to be sure that the the list of regexes completely covers the list of files as defined by the git man pages, since without comments it is not readily obvious which regex covers which files.

**Comment by tarsius** [comment]
I think the regexps are clear enough, so please drop the comments.

**Comment by npostavs** [comment]
I guess this can be merged now? (@sensorflo: pushing commits doesn't send a notification, so you should always comment after pushing).

**Comment by tarsius** [comment]
I've cherry-picked those now. Thanks and sorry for the delay.

**Pull request closed without merging**
