### PR TITLE
Improve indentation in gitconfig-mode.

### PR DESCRIPTION
**Pull request by johanclaesson**
1. Respect the value of indent-tabs-mode.  Insert TAB when it is non-nil
(default).  Insert spaces when it is nil.

2. Don't indent empty lines and comment lines.

3. If line is already indented properly and point was in the indentation
then move point to the end of indentation.  This is how most other modes
behave i think.

4. Free the temporary marker (old-point) at the end of
gitconfig-indent-line.

### CODE REVIEW

**Comment by tarsius** [comment]
Could you please split this up into multiple commits.

**Comment by johanclaesson** [comment]
Ok, i will close this pull request and create another.

**Comment by tarsius** [comment]
You can just force push to the same branch, no need to create a new pr (but you need to reopen this one).

**Comment by johanclaesson** [comment]
Ok, i did not know that.  I have deleted my fork of git-modes and created a new one. I hope that is also ok.

**Pull request closed without merging**
