### PR TITLE
Indent with spaces if indent-tabs-mode is nil

### PR DESCRIPTION
**Pull request by johanclaesson**
The default is still to indent with a tab.

### CODE REVIEW

**Comment by lunaryorn** [comment]
I'd just like to point out that `git config` always indents with tabs when it changes git config files.  For this reason I deliberately ignored `indent-tabs-mode` when I wrote this mode.

**Comment by tarsius** [comment]
Yes, I am aware of that and that's why I orginally rejected the first version of this change. Unfortunately very good at obfuscating code review so I cannot link to that discussion. (And I was hoping @johanclaesson would do so or rehash it for you, thus the delay).

His argument was that he maintains some gitconfig files completely by hand, and because he really likes spaces they contain no tabs. He then goes on including these files in other files (using `include.path` (didn't know about that before, something learned)).

The compromis is to keep setting `include-tabs-mode` to `t` in the mode but if a user then goes undoing that using the mode hook, then respect his choice.

**Comment by johanclaesson** [comment]
That is a good summary and 
here is the original discussion:

https://github.com/magit/git-modes/pull/122

Sorry for the delay and confusion.  This was my first github pull
request and i realize i did not do it in the best possible way.  In
particular i created new pull requests instead of reusing the first one.
Next time i will stick to the original pull request so that all
discussion is at one place.  Thanks for your patience :)

**Comment by npostavs** [comment]
> Next time i will stick to the original pull request so that all discussion is at one place.

Actually, since that discussion is linked to the commits, if you had reused the pull request by `push -f`, the original discussion would have been *even harder* to find. It would have been nice to link the related pull request/issues in the starting post.

**Comment by johanclaesson** [comment]
Ok, good to know.  Thanks for the advice.

**Comment by tarsius** [comment]
> https://github.com/magit/git-modes/pull/122

Ah, that's why I could not find it: I only looked at closed issues.

> Actually, since that discussion is linked to the commits,

And I thought Github found a new way of discarding potentially still relevant comments :-)

**Comment by lunaryorn** [comment]
@johanclaesson @npostavs @tarsius Oh, sorry, I didn't intend to start any discussion again, and I'm not against this change for sure.  I really just wanted to make sure that you are aware of why tabs were enforced.

**Comment by tarsius** [comment]
No problem and thanks for chiming in.

**Pull request merged**
