### PR TITLE
Added git commit mode 

### PR DESCRIPTION
**Pull request by rumatoest**
Source from rafl repository
With compatibility updates for Emacs 24.x (using cl-lib)

### CODE REVIEW

**Comment by tarsius** [comment]
No.

Use [this](https://github.com/magit/magit/blob/master/lisp/git-commit.el) instead.

**Comment by rumatoest** [comment]
There is no colors for git commit message.

**Comment by npostavs** [comment]
huh? what colours are you talking about?

**Comment by tarsius** [comment]
> There is no colors for git commit message.

So there is a bug or a misconfiguration. The proper thing to do then would be to figure out what is wrong, not to throw away the current implementation (with many fixed bugs and many new features) and going back to a version from several years ago.

**Comment by tarsius** [comment]
If you cannot figure it out on your own, then go to http://emacs.stackexchange.com/questions/tagged/magit and ask for help there (it might very well be @npostavs or me who help you there).

**Pull request closed without merging**
